spring:
  datasource:
    url: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ''
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081
